FROM alpine:latest

RUN apk update && \
    apk add krb5-server
RUN apk add openjdk8

COPY kdc-config.sh /var/lib/krb5kdc/
RUN chmod 777 /var/lib/krb5kdc/kdc-config.sh
EXPOSE 88/udp 749/udp

ENTRYPOINT [ "sh", "/var/lib/krb5kdc/kdc-config.sh"]