version: "3.7"
services:
   namenode:
      image: apache/hadoop:3.3.6
      hostname: namenode
      entrypoint: /start-namenode.sh
      command: ["hdfs", "namenode","yum install krb5-workstation"]
      ports:
        - 8020:8020
        - 9870:9870
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
      volumes:
          - server-keytab:/var/keytabs
          - /home/sagar/Desktop/hadoop/start-namenode.sh:/start-namenode.sh
   datanode:
      image: apache/hadoop:3.3.6
      hostname: datanode
      entrypoint: /start-datanode.sh
      command: ["hdfs", "datanode","yum install krb5-workstation"]
     
      env_file:
        - ./config     
      volumes:
        - server-keytab:/var/keytabs
        - /home/sagar/Desktop/hadoop/start-datanode.sh:/start-datanode.sh
        
   resourcemanager:
      image: apache/hadoop:3.3.6
      hostname: resourcemanager
      command: ["yarn", "resourcemanager","yum install krb5-workstation"]
      ports:
         - 8088:8088
      env_file:
        - ./config
      volumes:
        - server-keytab:/var/keytabs
   nodemanager:
      image: apache/hadoop:3.3.6
      command: ["yarn", "nodemanager","yum install krb5-workstation"]
      env_file:
        - ./config
      volumes:
        - server-keytab:/var/keytabs
   kerberos:
      hostname: kerberos
      entrypoint: /tmp/start-kdc.sh
      build:
        context: .
        args:
          - http_proxy
          - https_proxy
      volumes:
        - server-keytab:/var/keytabs
volumes:
    server-keytab:
