version: "3.7"
services:
   namenode:
      image: apache/hadoop:3.3.6
      hostname: namenode
      command: ["hdfs", "namenode"]
      
      ports:
        - 8020:8020
        - 9870:9870
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-hadoop/dfs/name"
      volumes:
        - /home/sagar/Desktop/hadoop/kdc/krb5.conf:/etc/krb5.conf
        - keytab:/var/keytabs/
        
      
   datanode:
      image: apache/hadoop:3.3.6
      hostname: datanode
      command: ["hdfs", "datanode"]
    
      env_file:
        - ./config     
      volumes:
        - /home/sagar/Desktop/hadoop/kdc/krb5.conf:/etc/krb5.conf     
        - keytab:/var/keytabs/
        
   resourcemanager:
      image: apache/hadoop:3.3.6
      hostname: resourcemanager
      command: ["yarn", "resourcemanager"]
      ports:
         - 8088:8088
      env_file:
        - ./config
      volumes:
        - /home/sagar/Desktop/hadoop/kdc/krb5.conf:/etc/krb5.conf
        - keytab:/var/keytabs/
        
      
   nodemanager:
      image: apache/hadoop:3.3.6
      command: ["yarn", "nodemanager"]
      env_file:
        - ./config
      
      volumes:
        - /home/sagar/Desktop/hadoop/kdc/krb5.conf:/etc/krb5.conf
        - keytab:/var/keytabs/
   kdc:
      build: 
        context: /home/sagar/Desktop/hadoop/kdc
        args:
         - http_proxy
         - https_proxy
      hostname: kdc
      volumes: 
        - keytab:/var/keytabs/
        
      ports:
       - 8081:88/udp
       - 8082:749/udp

volumes:
    keytab:    
        

