version: "3.7"
services:
   namenode:
      image: apache/hadoop:3.3.6
      command: ["hdfs", "namenode"]
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-hadoop/dfs/name"
      volumes:
        - ./krb5.conf:/etc/krb5.conf
        - keytab:/var/keytabs/
      network_mode: "host"


   datanode:
      image: apache/hadoop:3.3.6
      command: ["hdfs", "datanode"]
      env_file:
        - ./config 
      volumes:
        - ./krb5.conf:/etc/krb5.conf     
        - keytab:/var/keytabs/
      network_mode: "host"


   resourcemanager:
      image: apache/hadoop:3.3.6 
      command: ["yarn", "resourcemanager"]
      env_file:
        - ./config
      volumes:
        - ./krb5.conf:/etc/krb5.conf
        - keytab:/var/keytabs/
      network_mode: "host"


   nodemanager:
      image: apache/hadoop:3.3.6 
      command: ["yarn", "nodemanager"]
      env_file:
        - ./config
      volumes:
        - ./krb5.conf:/etc/krb5.conf
        - keytab:/var/keytabs/
      network_mode: "host"

       
   kdc:
      build: 
        context: ./kdc
      ports:
        - 8081:88/udp
        - 8082:749/udp
      volumes: 
        - keytab:/var/keytabs/
      
volumes:
    keytab:  




